contact_properties = {  'Nombre':'firstname',
                        'Apellido':'lastname',
                        'Tipo de Documento': 'id_o_passport',
                        'ID': 'number_of_id',
                        'Direccion':'adress',
                        'Telefono':'phone',
                        'Nacionalidad':'nationality'
                        'Localización dirección': ''
                        'Pais dirección': 'country_of_residence'
                        }
deal_properties={   'Nombre Proyecto': 'project_name',
                    'Numero Edificio':  'building',
                    'Nivel Edificio':  'building_level',
                    'Numero Apartamento': 'apartment_number',
                    'Superficie total': 'total_m2',
                    'Superficie interior': 'inner_surface',
                    'Superficie Terraza': 'balcony_surface',
                    'Numero habitaciones':'rooms_number',
                    'Numero baños':'bath_number',
                    'Precio base':'base_price',
                    'banco':'customer_bank_name',
                    'cuenta_bancaria':'bank_account',
                    'Reserva':'initial_paid_value',
                    'fecha_entrega':'delivery_date',
                    'descuento':'calculado a partir de amount (precio final)',
                    'num cuotas':'fee_number',
                    'porcentaje inicial':'calculado sobre amount (precio final)',
                    'porcentaje cuotas':'calculado total_fee_value sobre amount (precio final)',
                    'broker':'collaborator'
                }

deal_properties={   'proyecto': 'project_name',
                    'edificio':  'building',
                    'edificio': 'apartment_number',
                    'nombre clientes': 'vien del mapeo de propiedades asociadas',
                    'id broker': 'id del colaborador',
                    'broker': 'viene del mapeo de id de broker',
                    'poliza de seguro' : 'insurance_policy',
                    'fecha de inicio':'createdate',
                    'fecha ingreso reserva':'signal_payment_date',
                    'fecha contrato reserva':'reservation_contract_date',
                    'fecha ingreso inicial':'booking__payment_date',
                    'fecha firma contrato':'contract_date',
                    'estado del contrato':'contract_status',
                    'fecha_entrega':'delivery_date',
                    'precio de venta': 'amount',
                    'importe teorico reserva':'signal_value',
                    'importe real reserva': 'reservation_real_paid_value',
                    'diferencia reserva':'teorico menos real de la reserva',
                    'importe teorico inicial':'initial_paid_value',
                    'importe real inicial':'actual_amount_of_the_deposit',
                    'diferencia inicial': 'teorico menos real del inicial',
                    'cuenta de destino': 'bank_account',
                    'num cuotas':'fee_number',
                    'periodo de las cuotas': 'recurring_fee_period',
                    'total de las cuotas':'total_fee_value',
                    'porcentaje inicial':'calculado sobre amount (precio final)',
                    'porcentaje cuotas':'calculado total_fee_value sobre amount (precio final)',
                    'procentaje a la entrega':'calculado sobre amount (precio final)',
                    'id hubspot cliente':'hs_object_id',
                    'codigo sage':'sage_code',
                    'codigo sap':'sap_code',
                }

para calcular el plan de pagos necesitas el recurring_fee_period (periodicidad de la cuota)